[WEBSERVICE]
BASICURL=http://10.41.21.91:808/basic.webservice/WebService.asmx?wsdl
DBCONNURL=http://10.41.21.91:808/DBConnect.WebService/DBConnect.WebService.asmx?wsdl
LOGONURL=http://10.41.21.91:808/Tester.WebService/WebService.asmx?wsdl
TESTERURL=http://10.41.21.91:808/Tester.WebService/WebService.asmx?wsdl

[Stage]
Stagecode=AO
Workstation=ERLOGFA
Line=D8

[CATEGORY]
MACCategory=01
SASCategory=02
GUIDCategory=
CMSNCategory=03

[UNIQUESEQNAME]
ErrorLogSEQName=FUNCTIONEVENTID
FixtureIDSEQName=FIXTUREID

[option]
LogMode = false
Operator= Z13113003
Fixtureid=2222222
CheckSkill=0

[ReadFileConfig]
ATEFileType=0
#0:No file
#1:File is from ATE machineI Teradyne
#2:File is from ATE machineII Anglient
#3:Files are from ATE machine Teradyne. (TXT file and DAT file)
#4:Only record the file content
ATEFilePath=D:\center\sfcsfail
ATEFileSuffix=txt
ATEFile1Suffix=dat
ATEFileBackUp=0
#1:Enable Backup file;
#0:Disable Backup file;
FileBackUpPath=D:\center\failbackup
#Config the path for backup;
ATEFileDelete=0
#1:Enable delete file;
#0:Disable delete file;
#ATEFileLength=12000
#Config the length of ATE file
DisableGetLocForTo=1
#1:Disable Get LOC for key word "To"
#0:Get LOC for key word "To", Old logic
#For ATE File Type is ATE machineII Anglient

[PassCount]
MaxPassCount=10
#Config the maximal value of pass count

[ID_UPLOAD]
CATEGORY =16
CHECKUSED = 1

[CustomQuery]
SQL=SELECT * FROM SFCMO A ,SFCUSN B WHERE A.MO=B.MO
#SQL or View must contain USN Field, USN is the query condition