# ---------------------- Part Bin ----------------------
# "GOLDEN_BIN" is the key identifier, must exist and be unique.
#copy source_bin and rename as target_bin
#Tool modify target_file
[GOLDEN_BIN]
source_bin = Source_Golden.bin
target_bin = ETE_fru_data.bin

# ---------------------- Part CRC ----------------------
# "CRC_SETTING" is the key identifier for running CRC16, must exist and be unique.
# crc_address : CRC start address
# crc calucation range: crc_start to crc_end.
# crc type : reserve
[CRC_SETTING]
crc_address = 0x00B6
crc_start = 0x0000
crc_end = 0x00B3

# ---------------------- Part Parameter ----------------------
# [item] , item name has no space
# offset : user assign
# max_length : refer to tmp.txt.  The remaining bytes are filled with 0x20 (ASCII code for space) by user.
# source_txt : user assign
# Character Encoding : reserve

#19-100257   
[Meta_PCBA_Part_Number]
offset = 0x001F
max_length = 9
source_txt = CustomerPN_tmp.txt

#B91.04M10.000F
[ODM_JDM_PCBA_Part_Number]
offset = 0x003B
max_length = 14
source_txt = UPN_tmp.txt

#WK0F551001EN01
[ODM_JDM_PCBA_Serial_Number]
offset = 0x004B
max_length = 14
source_txt = SN_tmp.txt


#20260316 ,YYYYMMDD
[System_Manufacturing_Date]
offset = 0x0070
max_length = 8
source_txt = DATE_tmp.txt

#WUS
[PCB Manufacturer]
offset = 0x007A
max_length = 3
source_txt = PCBSupplier_tmp.txt



