# ---------------------- Part Bin ----------------------
# "GOLDEN_BIN" is the key identifier, must exist and be unique.
#copy source_bin and rename as target_bin
#Tool modify target_file
[GOLDEN_BIN]
source_bin = Netlake2-Golden-FBOSS-v6_20251107.bin
target_bin = your_eeprom_data.bin

# ---------------------- Part CRC ----------------------
# "CRC_SETTING" is the key identifier for running CRC16, must exist and be unique.
# crc_address : CRC start address
# crc calucation range: crc_start to crc_end.
# crc type : reserve
[CRC_SETTING]
crc_address = 0x009D
crc_start = 0x0000
crc_end = 0x009A

# ---------------------- Part Parameter ----------------------
# [item] , item name has no space
# offset : user assign
# max_length : refer to tmp.txt.  The remaining bytes are filled with 0x20 (ASCII code for space).
# source_txt : user assign
# Character Encoding : reserve

#19-100257   
[Meta_PCBA_Part_Number]
offset = 0x001F
max_length = 12
source_txt = CustomerPN_tmp.txt

#B91.04M10.000F
[ODM_JDM_PCBA_Part_Number]
offset = 0x003B
max_length = 14
source_txt = UPN_tmp.txt

#WK0F551001EN01
[ODM_JDM_PCBA_Serial_Number]
offset = 0x004C
max_length = 14
source_txt = SN_tmp.txt

#WUS
[PCB Manufacturer]
offset = 0x0060
max_length = 3
source_txt = PCBSupplier_tmp.txt



